### ISSUE TITLE
SCM triggering support

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparky#3]
I'd be good to have sparky builds get triggered by changes in SCM:

`sparky.yaml`:

```yaml
  scm:
   url: https://github.com/melezhik/rakudist-teddy-bear.git
   branch: main
```
