### ISSUE TITLE
Cascading between projects

### ISSUE THREAD

**Issue by thibaultduponchelle** [melezhik/sparky#34]
This is another one that comes from my mind.

Could we chain easily some projects "harmoniously". 
At the end of a running build, trigger one or more other projects, potentially passing one or more parameters (sha1 or tags).

It is often needed for docker image creation (one repo contains low level image, one contains technical and is built on top of low level one, one contains functional etc...).
It is also useful for version propagation.

It would be very cool to do not have to implement cascading mechanism by ourself through http form calls or auto git commit.

**Comment by melezhik** [comment]
Looks like it is implemented though a downstream projects, though it does not allow to pass parameters from one build to another ...

**Comment by thibaultduponchelle** [comment]
How are triggered downstream projects ? With file triggering protocol ? If yes it could embed parameters...

**Comment by melezhik** [comment]
yes, downstream projects are triggered by FTP [internally](https://github.com/melezhik/sparky/blob/master/bin/sparky-runner.raku#L340-L353), though a user can't pass anything from main build to downstream one. 

Maybe we could extend downstream semantic? 

For example:

`sparky.yaml`:

```yaml
downstream: downstream-project
  parameters:
    - var1 : config_var1 # pass var1 to downstream by reading config()<var1> in main project
    - var2 : "hello" # you may also pass values explicitly
    # so on ... 
```
